"""Immutable acquisition evidence. Interpretation happens only after archiving."""

import hashlib
import json
import re
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError
from urllib.parse import parse_qsl, urlsplit
from urllib.request import Request, urlopen

MAX_BYTES = 64 * 1024 * 1024


def fetch(url: str, root: Path, label: str, context: dict | None = None,
          timeout: float = 30) -> dict:
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    started = datetime.now(timezone.utc)
    timer = time.monotonic()
    item = {
        'url': url, 'method': 'GET', 'final_url': None,
        'query_parameters': [list(pair) for pair in parse_qsl(urlsplit(url).query, keep_blank_values=True)],
        'context': context or {}, 'started_at_utc': started.isoformat(),
        'http_status': None, 'response_headers': {}, 'diagnostics': [],
        'outcome': 'network_error', 'truncated': False,
    }
    body = b''
    try:
        request = Request(url, headers={'User-Agent': 'BrazilianBanksDataQualityPilot/0.1',
                                        'Accept-Encoding': 'identity'})
        try:
            response = urlopen(request, timeout=timeout)
        except HTTPError as error:
            response = error
        with response:
            item['http_status'] = response.status
            item['final_url'] = response.geturl()
            item['response_headers'] = dict(response.headers.items())
            body = response.read(MAX_BYTES + 1)
            if len(body) > MAX_BYTES:
                item['truncated'] = True
                item['diagnostics'].append('Response exceeded 64 MiB; truncated body is NOT an accepted dataset.')
            item['outcome'] = ('ok' if response.status == 200 and not item['truncated'] else 'http_error')
            if response.status != 200:
                item['diagnostics'].append(f'HTTP {response.status}; body retained without dataset acceptance.')
    except Exception as error:
        item['diagnostics'].append(f'{type(error).__name__}: {error}')
    item['retrieved_at_utc'] = datetime.now(timezone.utc).isoformat()
    item['elapsed_seconds'] = round(time.monotonic() - timer, 6)
    item['bytes'] = len(body)
    item['sha256'] = hashlib.sha256(body).hexdigest()
    safe_label = re.sub(r'[^a-zA-Z0-9_-]', '_', label)[:100]
    stem = f'{started.strftime("%Y%m%dT%H%M%S%fZ")}_{safe_label}_{uuid.uuid4().hex}'
    item['body_path'] = stem + '.bin'
    item['manifest_path'] = stem + '.json'
    with (root / item['body_path']).open('xb') as output:
        output.write(body)
    with (root / item['manifest_path']).open('x', encoding='utf-8') as output:
        json.dump(item, output, ensure_ascii=False, indent=2)
    return item


def load_body(manifest: dict, root: Path) -> bytes:
    body = (Path(root) / manifest['body_path']).read_bytes()
    if hashlib.sha256(body).hexdigest() != manifest['sha256']:
        raise ValueError('Archived body hash mismatch: ' + manifest['body_path'])
    return body


def preserve_generated(body: bytes, root: Path, label: str, source_url: str,
                       kind: str, context: dict | None = None) -> dict:
    """Archive browser-generated evidence without inventing an HTTP response."""
    root=Path(root); root.mkdir(parents=True,exist_ok=True)
    now=datetime.now(timezone.utc).isoformat()
    stem=re.sub(r'[^a-zA-Z0-9_-]','_',label)[:100]+'_'+uuid.uuid4().hex
    item={'url':source_url,'final_url':source_url,'method':'browser_export',
          'query_parameters':[list(p) for p in parse_qsl(urlsplit(source_url).query,keep_blank_values=True)],
          'context':context or {},'retrieved_at_utc':now,'http_status':None,'response_headers':{},
          'kind':kind,'outcome':'generated_evidence','diagnostics':['Generated by the official portal; not an HTTP response.'],
          'bytes':len(body),'sha256':hashlib.sha256(body).hexdigest(),'body_path':stem+'.bin','manifest_path':stem+'.json'}
    with (root/item['body_path']).open('xb') as out: out.write(body)
    with (root/item['manifest_path']).open('x',encoding='utf-8') as out: json.dump(item,out,ensure_ascii=False,indent=2)
    return item
